version: '3'
services:
  webapp:
    env_file:
      - ./.env
    volumes:
      - ./webapp:/usr/src/app
    build:
      context: ./webapp
      dockerfile: ./Dockerfile.production
    image: 741892569245.dkr.ecr.ap-northeast-2.amazonaws.com/sellon-webapp
    container_name: webapp-container
    entrypoint:
      - /docker-entrypoint.production.sh
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    image: 741892569245.dkr.ecr.ap-northeast-2.amazonaws.com/sellon-nginx
    container_name: nginx-container
    ports:
      - 80:80
    depends_on:
      - webapp
    links:
      - webapp
    entrypoint:
      - /docker-entrypoint.production.sh
